### ISSUE TITLE
Nintendo zone crashes before starting

### ISSUE THREAD

**Issue by jozhlogg** [MegaPika/Satellazone#1]
![IMG_1542](https://user-images.githubusercontent.com/7301060/167951698-41c6a1e9-71e4-4153-aa31-0e54a273bed7.jpeg)
![IMG_1543](https://user-images.githubusercontent.com/7301060/167951736-4b83455f-3051-4ed4-90ab-e2786053d6b3.jpeg)

When opening the title, I get the error in the second image, I don’t really know what this is but can post the dump of the error later if that’s useful. My region is Europe and I downloaded from universal updater if that makes any difference.

**Comment by TheGhostboi64** [comment]
We don't know what caused that problem. It shouldn't do that either. You might've messed up something that made it crash.

**Comment by 0megaplus** [comment]
Works fine for me also. But my console _was_ Japanese (now English) and I have no problem booting anyways.

**Comment by jozhlogg** [comment]
Seems odd, I only installed it from the universal updater and it started doing this. I do remember launching the Nintendo Zone app fine when I first set up CFW, so idk what caused the issue. I'll mark it as closed as it seems to be specific to me.

**Comment by MegaPika** [comment]
Hi sorry for late answer, did you do a region swap or something like this on your 3ds ?

**Comment by TheGhostboi64** [comment]
No response. Close it

**Comment by JaySea77** [comment]
This happens when you place the code.ips in the EUR folder. Not sure how to use the code.ips on the EUR version though.

**Comment by RubennRmPro** [comment]
This is the same issue i have.
