### ISSUE TITLE
Attempting to start Nintendo Zone fails

### ISSUE THREAD

**Issue by CCF100** [MegaPika/Satellazone#11]
Attempting to start Nintendo Zone fails with the message: "This service has been discontinued. Thank you for using this service."

**Comment by TheGhostboi64** [comment]
You need to download "usapatch.zip"

**Comment by Efadd** [comment]
Did you apply the usapatch? It does need to be done on another computer.

**Comment by CCF100** [comment]
I installed through Universal Updater so idk lol

**Comment by cooolgamer** [comment]
just download UsaPatch on universal updater, reboot and magic

**Comment by CCF100** [comment]
Closing because installing usapatch fixed it. Sorry for bothering you guys lol
