### ISSUE TITLE
An error has occurred, forcing the software to close

### ISSUE THREAD

**Issue by cjeziakor** [MegaPika/Satellazone#12]
I put the romfs folder in the title ID, I don't know where to put the USAPatch and after I did all of this, I've got a black screen and an error when I'm trying to go to satellazone.

**Comment by MegaPika** [comment]
Join the discord server if you still have this
https://discord.gg/csSWztn6z4

**Comment by cooolgamer** [comment]
you should not put this on nintendo zone but on homemenu
