### ISSUE TITLE
Nintendo Zone EUR Crashing When opening.

### ISSUE THREAD

**Issue by RubennRmPro** [MegaPika/Satellazone#15]
Hello,So recently i downloaded the EUR Version of satellazone,i installed the cia thorugh fbi and when i do the hotspot NintendoSpotPass1,The nintendo zone appears to be a black icon and when i open it the console crashes.
![IMG_20230330_145731](https://user-images.githubusercontent.com/89915872/229194134-f14f6ded-e056-4922-b424-c00b794ddec3.jpg)

**Comment by RubennRmPro** [comment]
#1 This is the same problem,i dont do a region transfer.

**Comment by cooolgamer** [comment]
We can't help about it since it involves downloading nintendo zone rom, but you can download the entire 3ds firmware by using 3DNUS then install all cias it downloaded with godmode9
Doing this have high chances to fix it

**Comment by RubennRmPro** [comment]
Whats 3DNUS
If you anserwer ill closed this

**Comment by RubennRmPro** [comment]
ok,now what,i downloaded it

**Comment by RubennRmPro** [comment]
ok,i downloaded the entire firmware of my version of 3ds,O3DS 11.16.0-49E.

**Comment by RubennRmPro** [comment]
im gonna istall all cias thorugh GM9,i will reopen this if something wents wrong,

**Comment by RubennRmPro** [comment]
OMG FINALLY YASSSSS
