### ISSUE TITLE
Europeans Version Satella Zone dont here in the home me'u

### ISSUE THREAD

**Issue by Kadir78382** [MegaPika/SatellaZone#17]
Hi , I have created thé hotspot NintendoSpotPass1 in my pc and Im connected in my 3ds I forces the connection at the correct slot but Nintendo Zone Dont Appair on the home menu please help D;

**Comment by MegaPika** [comment]
Hello, can you please join the discord server https://discord.gg/csSWztn6z4 so it will be easier to help you !

**Comment by Rix565** [comment]
...what?

**Comment by MegaPika** [comment]
i don't like talking on github XD
