### ISSUE TITLE
Why is there no source code?

### ISSUE THREAD

**Issue by ghost** [MegaPika/SatellaZone#18]

**Comment by spongetoo** [comment]
You could just get SatellaZone @ the releases page and open the files for it. Really ez than wasting your time asking questions about source codes 'n' stuff.

**Comment by ghost** [comment]
Romfs mods do not, and have not ever been reported on a 3ds to carry Malware.
Also, the source code shouldn't be shared, as Nintendo can take this down if they find anything relating to their property.
This would be taken down just like what had happened to Dolphin Emulator on Steam.

I am not sure exactly on how StellaZone works, but I would rather have it than not have it.

**Comment by cooolgamer** [comment]
There is no sourcecode because it's already on the romfs patch. If you want to see how it works, just look inside the patch, it's html pages and images, you can see them easily

**Comment by MegaPika** [comment]
> Romfs mods do not, and have not ever been reported on a 3ds to carry Malware. Also, the source code shouldn't be shared, as Nintendo can take this down if they find anything relating to their property. This would be taken down just like what had happened to Dolphin Emulator on Steam.
> 
> I am not sure exactly on how StellaZone works, but I would rather have it than not have it.

well here we patch the files directly and since nothing is encrypted you can modify everything like you want.
