### ISSUE TITLE
Patch Error Code 003-1099?

### ISSUE THREAD

**Issue by Yrouel** [MegaPika/SatellaZone#2]
When opening Nintendo Zone viewer this error pops up because it seems to be still trying to connect to the original Nintendo Zone servers despite the SatellaZone Luma patch (which to clarify is working fine) so it'll be nice to patch it out somehow.

I'm using an EUR New 2DS XL with Nintendo Zone viewer enabled using the hotspot trick.

**Comment by TheGhostboi64** [comment]
003-1099 (Nintendo 2DS/3DS)
Category
internet
Description
Access point with given SSID not found.
i'm not sure how to fix that sorry, neither the team does

**Comment by MegaPika** [comment]
Did you install SatellaZone and the Patch ? Because if you only install the Patch it's not gonna work

**Comment by Yrouel** [comment]
> Did you install SatellaZone and the Patch ? Because if you only install the Patch it's not gonna work

There is no EUR patch, I installed SatellaZone and after launching it with FBI got old I activated it with the hotspot trick.
So now I have Nintendo Zone viewer on the HOME Menu and it works fine except for that error I get first thing I open the app, in other words after I acknowledge that error I can use SatellaZone just fine however it'll be nice if it got patched if possible

**Comment by MegaPika** [comment]
The error is showing everytime when you open NintendoZone.
I don't think it can be patch sadly but yes it would be nicer to don't have the error.
https://cdn.discordapp.com/attachments/970017417164116008/976871551129497680/unknown.png
Like Cooolgamer did (check the link) you can replace the text with something else. (idk if it will be in SatellaZone)
