### ISSUE TITLE
Error: 013-8404 bug(?)

### ISSUE THREAD

**Issue by 0megaplus** [MegaPika/Satellazone#3]
Upon starting Nintendo Zone with the latest version, I am greeted with 2 error messages:

1. The error message reporting that there is no Nintendo Zone AP nearby. This is probably natural.
2. An error message saying that a "specified file" is not on the "server". I have no idea what this means. My friends' hacked 3DS works fine, and does not show the second error. 

Is this a bug in my console? It is JPN New 3DS XL, region changed. Or does it have a fix? 

SCREENSHOT:
![nintenzoneerror-top - Copy](https://user-images.githubusercontent.com/97362960/169143447-299190f2-205e-41ae-9fe0-64495e9cfa62.png)
![nintenzoneerror-bot - Copy](https://user-images.githubusercontent.com/97362960/169143486-40598e88-3b3a-48b7-9cb0-b12ed0401110.png)

Any info helps if it relates to this question.
Thanks, Omega207

**Comment by MegaPika** [comment]
Hi so is it with SatellaZone or without that cause the problem ?

**Comment by MegaPika** [comment]
Oh i'm dumb, ok It's really weird does it still does the same without SatellaZone ?
The region change could also be an issue a lot of people that change the region got problems with it.

**Comment by 0megaplus** [comment]
Ok, it does do the same without SatellaZone as well. I guess it is an error with Nintendo Zone itself. Could deleting all save data fix this or something?

**Comment by MegaPika** [comment]
I think it's an error that is cause by the region swap.
If you restore a nand backup it probably gonna work again but for make it work on region swap i don't know try to reinstall the app with a .cia .

**Comment by 0megaplus** [comment]
Okay, thanks. I'll look into it soon.
