### ISSUE TITLE
Error 013-8000

### ISSUE THREAD

**Issue by ErgFox3DS** [MegaPika/Satellazone#5]
I set up the hospot but not work:

Name hospot: NintendoSpotPass1
Without password

Console: 2ds old eur 
Package: eur

**Comment by cooolgamer** [comment]
if the error happens when you open Nintendo zone, ignore it

**Comment by TheSandBoxMKG** [comment]
It happens on a US Old 2DS everytime I try to watch any video. Same hotspot configuration (NintendoSpotPass1 without password), and it takes a long time trying to connect before the error shows. Language is set to Spanish.

EDIT: Also, the Old 2DS interacts differently with the same hotspot when named NintendoSpotPass1 than when named with the default name (haven't tried any other name than the default, NintendoSpotPass1 and NintendoSpotPass2), failing to even connect to the hotspot despite being allowed in the MAC filter list and being passwordless.

EDIT 2: Also Nintendo Zone doesn't even detect any hotspot named NintendoSpotPass2.

**Comment by TheGhostboi64** [comment]
> It happens on a US Old 2DS everytime I try to watch any video. Same hotspot configuration (NintendoSpotPass1 without password), and it takes a long time trying to connect before the error shows. Language is set to Spanish.
> 
> EDIT: Also, the Old 2DS interacts differently with the same hotspot when named NintendoSpotPass1 than when named with the default name (haven't tried any other name than the default, NintendoSpotPass1 and NintendoSpotPass2), failing to even connect to the hotspot despite being allowed in the MAC filter list and being passwordless.
> 
> EDIT 2: Also Nintendo Zone doesn't even detect any hotspot named NintendoSpotPass2.

You need to use the SSL Patch. https://github.com/InternalLoss/3DS-SSL-Patch

**Comment by TheGhostboi64** [comment]
And you aren't supposed to connect to the hotspot from system settings. Nintendo Zone automatically connects to it.

**Comment by cooolgamer** [comment]
I forgot, it require SSL patch here: https://github.com/InternalLoss/3DS-SSL-Patch, use it and it should work, also do not connect to the hotspot on system settings

**Comment by TheSandBoxMKG** [comment]
@cooolgamer I haven't managed to get Nintendo Zone to connect to the NintendoSpotPass1 hotspot even when removing the hotspot from system settings and using the SSL patch.

(I have put the code.ips file in it's correct place and ~~I have checked the patch works by visiting GBATemp with another hotspot~~ (nevermind, GBATemp still works even without the patch though visiting Google doesn't give me "you are visiting an unencrypted page" without the patch while it does with the patch, so I'm not sure if it's working properly) but I don't know where to put the ClCertA.p12 file)

**Comment by TheGhostboi64** [comment]
close this

**Comment by MysticAx0lotl** [comment]
I have the same issue, even after setting up a hotspot correctly and installing the SSL patch.

**Comment by MegaPika** [comment]
Weird you can’t watch the videos ? Just click ok don’t think about the error. (Sorry i forgot to answer)

**Comment by MysticAx0lotl** [comment]
> Weird you can’t watch the videos ? Just click ok don’t think about the error. (Sorry i forgot to answer)

I did, and it either hangs on an infinite loading screen (I think), or gives another error

**Comment by MegaPika** [comment]
Mmm weird, do you have discord ? If yes please join the discord server it’s gonna be easier to talk here

**Comment by MysticAx0lotl** [comment]
> Mmm weird, do you have discord ? If yes please join the discord server it’s gonna be easier to talk here

I do, and I will. Ty!

**Comment by MegaPika** [comment]
https://discord.gg/csSWztn6z4
