### ISSUE TITLE
Change how contributions work.

### ISSUE THREAD

**Issue by ghost** [MegaPika/Satellazone#8]
I think all of the assets for SatellaZone (PNG, HTML etc etc) need to be on this github repo or at least on a separate repo to allow users to contribute to the SatellaZone project, and to make development slightly easier.
Just something to consider. Also someone wants to add some assets into SattellaZone: #6 

lemme know if you want to talk about this on discord

**Comment by MegaPika** [comment]
Yes. (gonna update tomorrow)

**Comment by MegaPika** [comment]
Unfortunately I can't do it because of github limitations :/ sorry about that

**Comment by ghost** [comment]
Larger files can be committed via LFS. You just have to enable it
